<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWC637Me\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWC637Me/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWC637Me.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWC637Me\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWC637Me\App_KernelDevDebugContainer([
    'container.build_hash' => 'WC637Me',
    'container.build_id' => '54a01aa5',
    'container.build_time' => 1658145565,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWC637Me');
